/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    Caldar: typeof import('./src/components/Caldar.vue')['default']
    Cardteam: typeof import('./src/components/Cardteam.vue')['default']
    DriverResult: typeof import('./src/components/DriverResult.vue')['default']
    Driversall: typeof import('./src/components/Driversall.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Nav: typeof import('./src/components/Nav.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Table: typeof import('./src/components/Table.vue')['default']
    Table2: typeof import('./src/components/Table2.vue')['default']
    Team: typeof import('./src/components/Team.vue')['default']
  }
}
